import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import worker from '../worker/index.js';
const sqlite = new DatabaseSync(':memory:');
sqlite.exec(readFileSync(new URL('../database/schema.sql', import.meta.url), 'utf8'));
const DB = { prepare(sql) { return { bind(...args) { this.args = args; return this; }, async first() { return sqlite.prepare(sql).get(...(this.args || [])) || null; }, async all() { return { results: sqlite.prepare(sql).all(...(this.args || [])) }; } }; } };
const request = (method, path = '', body) => worker.fetch(new Request('https://example.test/api/weapons' + path, { method, ...(body === undefined ? {} : { headers: { 'content-type':'application/json' }, body: JSON.stringify(body) }) }), { DB });
const weapon = { name: '  ŻELAZNY   MIECZ ', attackDice: 2, attackBonus: 1, bonusDamage: 0, perHit: { red:1, black:0, white:0 }, extraDice: { red:0, black:0, white:0 } };
let response = await request('POST', '', weapon);
assert.equal(response.status, 201);
const created = (await response.json()).weapon;
assert.equal(created.name, 'ŻELAZNY MIECZ');
assert.equal((await request('POST', '', { ...weapon, name:'żelazny miecz' })).status, 409);
assert.equal((await request('GET')).status, 200);
response = await request('POST', '', { ...weapon, name:'Topór' });
const second = (await response.json()).weapon;
assert.equal((await request('PUT', '/' + second.id, { ...weapon, name:'Żelazny miecz' })).status, 409);
assert.equal((await request('PUT', '/' + created.id, { ...weapon, name:'Żelazny miecz', attackDice:3 })).status, 200);
assert.equal((await request('PUT', '/' + created.id, { ...weapon, name:'Szabla' })).status, 200);
assert.equal((await request('POST', '', { ...weapon, name:'Żelazny miecz' })).status, 201);
assert.equal((await request('POST', '', { ...weapon, attackDice:1.5 })).status, 400);
assert.equal((await request('PUT', '/999999', weapon)).status, 404);
assert.equal((await request('DELETE', '/' + second.id)).status, 204);
assert.equal((await request('DELETE', '/' + second.id)).status, 404);
assert.equal((await request('DELETE')).status, 405);
assert.equal((await request('GET', '/bad')).status, 404);
const raced = await Promise.all([request('POST', '', { ...weapon, name:'ŁUK' }), request('POST', '', { ...weapon, name:'łuk' })]);
assert.deepEqual(raced.map(r => r.status).sort(), [201,409]);
assert.equal(sqlite.prepare('SELECT count(*) AS n FROM weapons WHERE name_key = ?').get('łuk').n, 1);
console.log('Weapons API: create, edit, delete, validation, normalized duplicates and concurrent writes passed.');
sqlite.close();
